#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) == 4:
	path = sys.argv[1]
	name = sys.argv[2]
	value = sys.argv[3]
elif len(sys.argv) == 3:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
					'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	name = sys.argv[1]
	value = sys.argv[2]
else:
	print("%s [PATH] name value" % (sys.argv[0]))
	sys.exit(0)

print("Setting {} as {} for modem {}..." .format(name, value, path))
lte = dbus.Interface(bus.get_object('org.ofono', path),
			'org.ofono.LongTermEvolution')
lte.SetProperty(name, value)
